[]
args.client_id_list = None
training_type != FEDML_TRAINING_PLATFORM_CROSS_DEVICE and training_type != FEDML_TRAINING_PLATFORM_CROSS_SILO
bsize is 128
[FedML-Server(0) @device-id-0] [Mon, 16 Jan 2023 22:42:58] [INFO] [__init__.py:109:print_args] ==== args = {'yaml_config_file': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml', 'run_id': '0', 'rank': 0, 'local_rank': 0, 'node_rank': 0, 'role': 'client', 'central_training': 0, 'yaml_paths': ['/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml'], 'training_type': 'simulation', 'random_seed': 0, 'dataset': 'ICU', 'data_cache_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/eICU_Data/', 'partition_method': 'hetero', 'partition_alpha': 0.5, 'model': 'GRU', 'input_dim': 128, 'hidden_dim': 32, 'num_layers': 2, 'output_dim': 1, 'dropout_prob': 0.05, 'dist_model_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/', 'central_model_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/central_training/', 'federated_optimizer': 'FedAvg', 'client_id_list': '[]', 'client_num_in_total': 10, 'client_num_per_round': 3, 'comm_round': 5, 'epochs': 2, 'batch_size': 128, 'client_optimizer': 'adamw', 'learning_rate': 0.005, 'weight_decay': 0.005, 'recruitment': True, 'div_weight': 0.5, 'inst_weight': 0.5, 'repr_perc': 0.2, 'central_epochs': 15, 'frequency_of_the_test': 1, 'using_gpu': False, 'gpu_id': 0, 'backend': 'sp', 'log_file_dir': '/Users/vscheltjens/fedml-server/fedml/logs', 'enable_wandb': True, 'wandb_key': '8d579c56c0eda8929353aac11d399b96e5aa9e71', 'wandb_entity': 'vs-health', 'wandb_project': 'federated_gru_eicu', 'central_wandb_project': 'recr_central_training', 'worker_num': 3, 'sys_perf_profiling': True, 'config_version': 'release', 'current_running_dir': '/Users/vscheltjens/fedml-client', 'os_name': 'MacOS', 'version': 'release', 'device_id': '0xC02F52N9MD6R', 'cloud_region': '', 'mqtt_config_path': '', 's3_config_path': '', 'log_server_url': 'https://open.fedml.ai/fedmlLogsServer/logs/update'}
[FedML-Server(0) @device-id-0] [Mon, 16 Jan 2023 22:42:58] [INFO] [ml_engine_adapter.py:147:get_torch_device] args = <fedml.arguments.Arguments object at 0x7f9468040f70>, using_gpu = False, device_id = 0, device_type = cpu
[FedML-Server(0) @device-id-0] [Mon, 16 Jan 2023 22:42:58] [INFO] [device.py:48:get_device] device = cpu
Loaded Global dataloaders
81135 24698
Loading previously stored local training data
[FedML-Server(0) @device-id-0] [Mon, 16 Jan 2023 22:43:40] [ERROR] [mlops_runtime_log.py:34:handle_exception] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/federated.py", line 24, in <module>
    dataset, args = update_dataset_args(args, client_list, dataset)
ValueError: too many values to unpack (expected 2)
The recruited clients (4) for the federation are [1, 4, 2, 5]